# Performance Analyzer Plugin Settings
metricsLocation=/dev/shm/performanceanalyzer/
metricsDeletionInterval=1
httpsEnabled=false
cleanup-metrics-db-files=false
batch-metrics-retention-period-minutes=7
rpc-port=9650
webservice-port=9600 